import { StyleSheet, Dimensions, Platform } from "react-native";
import { colors } from "@/Theme/colors";

const { width, height } = Dimensions.get("window");
const imageSize = width - 60;
const maxContentWidth = Math.min(width * 0.9, 500);

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  holder: {
    borderRadius: 16,
  },
  card: {
    width: maxContentWidth,
    backgroundColor: colors.background,
    borderRadius: 20,
    paddingTop: 40,
    paddingHorizontal: 20,
    alignItems: "center",
    paddingBottom: 30,
    alignSelf: "center",
  },
  closeButtonAbsolute: {
    position: "absolute",
    backgroundColor: colors.primary,
    top: 5,
    right: 10,
    borderRadius: 16,
    padding: 0.0,
    elevation: 4,
    shadowRadius: 4,
    zIndex: 10,
  },
  image: {
    width: imageSize,
    height: imageSize,
    borderRadius: 16,
    backgroundColor: "#f9f9f9",
    alignSelf: "center",
  },
  noImage: {
    width: imageSize,
    height: imageSize,
    borderRadius: 16,
    backgroundColor: "#eee",
    alignSelf: "center",
    marginBottom: 10,
  },
  name: {
    fontSize: 16,
    color: colors.text,
    textAlign: "center",
    marginTop: 8,
  },
  code: {
    fontSize: 13,
    color: colors.primary,
    textAlign: "center",
    marginTop: 2,
  },
  imageCount: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
    marginTop: 4,
  },
  divider: {
    height: 1,
    backgroundColor: "#e4e4e4",
    width: "85%",
    marginVertical: 12,
  },
  descriptionHtml: {
    fontSize: 13.3,
    color: "#333",
    lineHeight: 24,
    textAlign: "center",
    alignSelf: "center",
    maxWidth: Math.min(width * 0.7, 440),
    fontFamily: "Tajawal",
    letterSpacing: Platform.OS === "android" ? 0.2 : 0.15,
    writingDirection: "rtl",
    marginTop: 8,
  },
  toggleDescription: {
    marginTop: 8,
    fontSize: 13,
    color: colors.primary,
    fontWeight: "600",
    textAlign: "center",
  },
  buttonsInline: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    marginTop: 20,
    width: "100%",
    gap: 60,
  },
  uploadBtn: {
    flex: 1,
    backgroundColor: "#333",
    paddingVertical: 10,
    borderRadius: 30,
    marginRight: 10,
    elevation: 2,
  },
  editBtn: {
    flex: 1,
    backgroundColor: "#333",
    paddingVertical: 10,
    borderRadius: 30,
    marginLeft: 10,
    elevation: 2,
  },
  uploadBtnText: {
    fontWeight: "bold",
    color: "#fff",
    fontSize: 12,
    textAlign: "center",
  },
  editBtnText: {
    fontWeight: "bold",
    color: "#fff",
    fontSize: 12,
    textAlign: "center",
  },
  loadingIndicator: {
    paddingVertical: 60,
  },
  errorText: {
    marginTop: 40,
    fontSize: 14,
    color: "#999",
    textAlign: "center",
  },
  fullImageWrapper: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.8)",
    width,
    height,
  },
  fullImage: {
    width: width * 0.9,
    height: height * 0.65,
    borderRadius: 16,
    backgroundColor: "#fff",
  },
  menuButtonAbsolute: {
    position: "absolute",
    textAlign: "center",
    top: 5,
    left: 10,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 3,
    borderWidth: 2.5,
    borderColor: colors.primary,
    elevation: 4,
    zIndex: 10,
  },
  statusMenuWrapper: {
    position: "absolute",
    flexDirection: 'row',
    top: 3,
    left: 50,
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 6,
    elevation: 6,
    zIndex: 10,
    gap: 10,
  },
  statusIconWrapper: {
    padding: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  statusIcon: {
    width: 20,
    height: 20,
    borderRadius: 21,
  },
  statusDivider: {
    width: 1.5,
    height: 18,
    backgroundColor: colors.primary,
    alignSelf: 'center',
    borderRadius: 1,
  },
  arrowIndicatorWrapper: {
    position: 'absolute',
    top: 5.5, 
    left: 30,
    zIndex: 11,
  },
  statusIconFixed: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    backgroundColor: '#fff',
    borderRadius: 20,
    elevation: 4,
  },
  statusIconImage: {
    width: 70,
    height: 70,
    borderRadius: 20,
  },
});
